### ISSUE TITLE
Analizar necesidad de cliente y documentar Story Telling

### ISSUE THREAD

**Issue by kavisch** [kavisch/HeladosBon#1]

**Comment by AlejandroBeltre** [comment]
Anexo el análisis de la necesidad del cliente junto a su historia de usuario tanto del desarrollador como del mismo cliente a este mensaje.

# Análisis de necesidad del cliente

## Situación Actual

- Las heladerías utilizan un formulario en papel para realizar un checklist diario.
- El formulario cubre procesos de apertura, operación durante el día y cierre.
- Se registra información por días de la semana y por quien realizó las tareas.
- Existe una app llamada MoreAPP para la gestión de heladerías por parte de los ejecutivos.

## Necesidad Identificada

El cliente desea digitalizar el proceso de checklist diario de las heladerías, pasando de un formato en papel a un formulario web utilizando React para el frontend, .NET Core para el backend, y MySQL como base de datos.

## Objetivos

1. Crear una versión web del formulario existente utilizando React.
2. Desarrollar un backend con .NET Core y C#.
3. Implementar una base de datos MySQL para almacenar la información.
4. Mantener la estructura de información del formulario original.
5. Facilitar el registro de tareas por turno y día de la semana a través de una interfaz web reactiva.
6. Asegurar la accesibilidad del formulario desde diferentes dispositivos con conexión a internet.
7. Posibilitar la integración con la app MoreAPP para reports

### HU01 - Desarrollador

Como desarrollador, quiero implementar una solución web completa para digitalizar el proceso de checklist diario de las heladerías, utilizando React, .NET Core y MySQL.

**Criterios de Aceptación:**

1. El proyecto React se ejecuta sin errores en ambiente local.
2. El proyecto .NET Core se conecta exitosamente a la base de datos MySQL.
3. Existe un repositorio Git con la estructura del proyecto y ramas para desarrollo y producción.
4. Las herramientas de desarrollo (ESLint, Prettier, react-hook-form, Ant Design, react-router, react-testing-library para React; Swagger , [[xUnit.net](http://xunit.net/)](http://xUnit.net) para .NET, Selenium para pruebas end-to-end, GithubActions para automatizaciones CI/CD) están configuradas y funcionando.

**Tareas:**

- Configurar el proyecto React utilizando Create React App o Next.js
- Establecer el proyecto .NET Core y configurar la conexión con MySQL
- Crear un repositorio Git y establecer la estructura del proyecto
- Configurar herramientas de desarrollo:
    - React:
        - ESLint.
        - Prettier.
        - react-hook-form.
        - Ant Design.
        - react-router.
        - react-testing-library.
    - .NET:
        - Swagger.
        - [xUnit.net](http://xunit.net/).
    - App:
        - Selenium.
        - Github Actions.

**Test Cases:**

- TC01: Verificar la correcta configuración del entorno de desarrollo
- TC02: Comprobar la conexión exitosa entre .NET Core y MySQL

### HU02 - Encargado de heladería

Como encargado de heladerías, quiero ver un prototipo inicial del formulario web que refleje la estructura del formulario en papel actual.

**Criterios de Aceptación:**

1. El prototipo muestra todas las secciones del formulario actual (apertura, operación, cierre).
2. La interfaz es intuitiva y fácil de navegar en dispositivos móviles y de escritorio.
3. El diseño refleja la identidad visual de la marca de heladerías.
4. Se pueden ingresar datos de prueba en el formulario para simular su uso real.

**Tareas:**

- Diseñar wireframes de la interfaz de usuario
- Crear componentes React básicos para el formulario
- Implementar diseño responsive utilizando Ant Design
- Desarrollar prototipo interactivo del formulario

**Test Cases:**

- TC03: Validar que el prototipo incluye todas las secciones del formulario actual
- TC04: Verificar la usabilidad en dispositivos móviles y de escritorio

**Comment by AlejandroBeltre** [comment]
Considero que esto debería caer dentro de un único sprint que sería el primero y abarcaría la configuración del proyecto y un diseño inicial del mismo.
